name: Build, Scan, Push and Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # ✅ Checkout source code
    - name: Checkout source code
      uses: actions/checkout@v3

    # ✅ SonarQube Static Analysis
    # - name: SonarQube Scan
    #   uses: sonarsource/sonarqube-scan-action@master
    #   env:
    #     SONAR_TOKEN: sqa_ff6b0e2ce9ac3d601a3d2e8d15ac7cfd6f42e077
    #     SONAR_HOST_URL: http://localhost:9000
    #   with:
    #     projectBaseDir: .

    # ✅ SonarQube Quality Gate
    # - name: Wait & Check Quality Gate
    #   uses: sonarsource/sonarqube-quality-gate-action@master
    #   env:
    #     SONAR_TOKEN: sqa_ff6b0e2ce9ac3d601a3d2e8d15ac7cfd6f42e077
    #     SONAR_HOST_URL: http://localhost:9000/

    # ✅ Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # ✅ Login to Docker Hub Account
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: fkfiroj
        password: Docker@@##

    # ✅ Build Docker Image
    - name: Build Docker image
      run: |
        docker build -t fkfiroj/laravel-app:${{ github.sha }} .

    # ✅ Trivy Security Scan
    - name: Trivy Vulnerability Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: fkfiroj/laravel-app:${{ github.sha }}
        format: table
        exit-code: 1
        severity: CRITICAL,HIGH
        ignore-unfixed: true
        # ignore-policy: .trivyignore

    # ✅ Push Docker Image (only if Trivy passes)
    - name: Push Docker image
      run: |
        docker push fkfiroj/laravel-app:${{ github.sha }}

    